// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/fraud/fraud.proto

package fraud

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FraudRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudRequest) Reset() {
	*x = FraudRequest{}
	mi := &file_proto_fraud_fraud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudRequest) ProtoMessage() {}

func (x *FraudRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_fraud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudRequest.ProtoReflect.Descriptor instead.
func (*FraudRequest) Descriptor() ([]byte, []int) {
	return file_proto_fraud_fraud_proto_rawDescGZIP(), []int{0}
}

func (x *FraudRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *FraudRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FraudRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FraudRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FraudResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsRisky       bool                   `protobuf:"varint,1,opt,name=is_risky,json=isRisky,proto3" json:"is_risky,omitempty"`
	RiskScore     float32                `protobuf:"fixed32,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Results       []*RuleResult          `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudResponse) Reset() {
	*x = FraudResponse{}
	mi := &file_proto_fraud_fraud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudResponse) ProtoMessage() {}

func (x *FraudResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_fraud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudResponse.ProtoReflect.Descriptor instead.
func (*FraudResponse) Descriptor() ([]byte, []int) {
	return file_proto_fraud_fraud_proto_rawDescGZIP(), []int{1}
}

func (x *FraudResponse) GetIsRisky() bool {
	if x != nil {
		return x.IsRisky
	}
	return false
}

func (x *FraudResponse) GetRiskScore() float32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *FraudResponse) GetResults() []*RuleResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type RiskReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Urgency       string                 `protobuf:"bytes,3,opt,name=urgency,proto3" json:"urgency,omitempty"` // LOW, MEDIUM, HIGH
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskReport) Reset() {
	*x = RiskReport{}
	mi := &file_proto_fraud_fraud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskReport) ProtoMessage() {}

func (x *RiskReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_fraud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskReport.ProtoReflect.Descriptor instead.
func (*RiskReport) Descriptor() ([]byte, []int) {
	return file_proto_fraud_fraud_proto_rawDescGZIP(), []int{2}
}

func (x *RiskReport) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RiskReport) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RiskReport) GetUrgency() string {
	if x != nil {
		return x.Urgency
	}
	return ""
}

type RiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskResponse) Reset() {
	*x = RiskResponse{}
	mi := &file_proto_fraud_fraud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskResponse) ProtoMessage() {}

func (x *RiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_fraud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskResponse.ProtoReflect.Descriptor instead.
func (*RiskResponse) Descriptor() ([]byte, []int) {
	return file_proto_fraud_fraud_proto_rawDescGZIP(), []int{3}
}

func (x *RiskResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type RuleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleName      string                 `protobuf:"bytes,1,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Passed        bool                   `protobuf:"varint,2,opt,name=passed,proto3" json:"passed,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleResult) Reset() {
	*x = RuleResult{}
	mi := &file_proto_fraud_fraud_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleResult) ProtoMessage() {}

func (x *RuleResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_fraud_fraud_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleResult.ProtoReflect.Descriptor instead.
func (*RuleResult) Descriptor() ([]byte, []int) {
	return file_proto_fraud_fraud_proto_rawDescGZIP(), []int{4}
}

func (x *RuleResult) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *RuleResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *RuleResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_fraud_fraud_proto protoreflect.FileDescriptor

const file_proto_fraud_fraud_proto_rawDesc = "" +
	"\n" +
	"\x17proto/fraud/fraud.proto\x12\x05fraud\"\x82\x01\n" +
	"\fFraudRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"v\n" +
	"\rFraudResponse\x12\x19\n" +
	"\bis_risky\x18\x01 \x01(\bR\aisRisky\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x02R\triskScore\x12+\n" +
	"\aresults\x18\x03 \x03(\v2\x11.fraud.RuleResultR\aresults\"W\n" +
	"\n" +
	"RiskReport\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\aurgency\x18\x03 \x01(\tR\aurgency\"2\n" +
	"\fRiskResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"[\n" +
	"\n" +
	"RuleResult\x12\x1b\n" +
	"\trule_name\x18\x01 \x01(\tR\bruleName\x12\x16\n" +
	"\x06passed\x18\x02 \x01(\bR\x06passed\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x83\x01\n" +
	"\fFraudService\x12=\n" +
	"\x10CheckTransaction\x12\x13.fraud.FraudRequest\x1a\x14.fraud.FraudResponse\x124\n" +
	"\n" +
	"ReportRisk\x12\x11.fraud.RiskReport\x1a\x13.fraud.RiskResponseB4Z2github.com/sapliy/fintech-ecosystem/proto/fraudb\x06proto3"

var (
	file_proto_fraud_fraud_proto_rawDescOnce sync.Once
	file_proto_fraud_fraud_proto_rawDescData []byte
)

func file_proto_fraud_fraud_proto_rawDescGZIP() []byte {
	file_proto_fraud_fraud_proto_rawDescOnce.Do(func() {
		file_proto_fraud_fraud_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_fraud_fraud_proto_rawDesc), len(file_proto_fraud_fraud_proto_rawDesc)))
	})
	return file_proto_fraud_fraud_proto_rawDescData
}

var file_proto_fraud_fraud_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_fraud_fraud_proto_goTypes = []any{
	(*FraudRequest)(nil),  // 0: fraud.FraudRequest
	(*FraudResponse)(nil), // 1: fraud.FraudResponse
	(*RiskReport)(nil),    // 2: fraud.RiskReport
	(*RiskResponse)(nil),  // 3: fraud.RiskResponse
	(*RuleResult)(nil),    // 4: fraud.RuleResult
}
var file_proto_fraud_fraud_proto_depIdxs = []int32{
	4, // 0: fraud.FraudResponse.results:type_name -> fraud.RuleResult
	0, // 1: fraud.FraudService.CheckTransaction:input_type -> fraud.FraudRequest
	2, // 2: fraud.FraudService.ReportRisk:input_type -> fraud.RiskReport
	1, // 3: fraud.FraudService.CheckTransaction:output_type -> fraud.FraudResponse
	3, // 4: fraud.FraudService.ReportRisk:output_type -> fraud.RiskResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_fraud_fraud_proto_init() }
func file_proto_fraud_fraud_proto_init() {
	if File_proto_fraud_fraud_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_fraud_fraud_proto_rawDesc), len(file_proto_fraud_fraud_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_fraud_fraud_proto_goTypes,
		DependencyIndexes: file_proto_fraud_fraud_proto_depIdxs,
		MessageInfos:      file_proto_fraud_fraud_proto_msgTypes,
	}.Build()
	File_proto_fraud_fraud_proto = out.File
	file_proto_fraud_fraud_proto_goTypes = nil
	file_proto_fraud_fraud_proto_depIdxs = nil
}
