// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: proto/fraud/fraud.proto

package fraud

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FraudService_CheckTransaction_FullMethodName = "/fraud.FraudService/CheckTransaction"
	FraudService_ReportRisk_FullMethodName       = "/fraud.FraudService/ReportRisk"
)

// FraudServiceClient is the client API for FraudService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FraudServiceClient interface {
	CheckTransaction(ctx context.Context, in *FraudRequest, opts ...grpc.CallOption) (*FraudResponse, error)
	ReportRisk(ctx context.Context, in *RiskReport, opts ...grpc.CallOption) (*RiskResponse, error)
}

type fraudServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFraudServiceClient(cc grpc.ClientConnInterface) FraudServiceClient {
	return &fraudServiceClient{cc}
}

func (c *fraudServiceClient) CheckTransaction(ctx context.Context, in *FraudRequest, opts ...grpc.CallOption) (*FraudResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FraudResponse)
	err := c.cc.Invoke(ctx, FraudService_CheckTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fraudServiceClient) ReportRisk(ctx context.Context, in *RiskReport, opts ...grpc.CallOption) (*RiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskResponse)
	err := c.cc.Invoke(ctx, FraudService_ReportRisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FraudServiceServer is the server API for FraudService service.
// All implementations must embed UnimplementedFraudServiceServer
// for forward compatibility.
type FraudServiceServer interface {
	CheckTransaction(context.Context, *FraudRequest) (*FraudResponse, error)
	ReportRisk(context.Context, *RiskReport) (*RiskResponse, error)
	mustEmbedUnimplementedFraudServiceServer()
}

// UnimplementedFraudServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFraudServiceServer struct{}

func (UnimplementedFraudServiceServer) CheckTransaction(context.Context, *FraudRequest) (*FraudResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckTransaction not implemented")
}
func (UnimplementedFraudServiceServer) ReportRisk(context.Context, *RiskReport) (*RiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportRisk not implemented")
}
func (UnimplementedFraudServiceServer) mustEmbedUnimplementedFraudServiceServer() {}
func (UnimplementedFraudServiceServer) testEmbeddedByValue()                      {}

// UnsafeFraudServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FraudServiceServer will
// result in compilation errors.
type UnsafeFraudServiceServer interface {
	mustEmbedUnimplementedFraudServiceServer()
}

func RegisterFraudServiceServer(s grpc.ServiceRegistrar, srv FraudServiceServer) {
	// If the following call panics, it indicates UnimplementedFraudServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FraudService_ServiceDesc, srv)
}

func _FraudService_CheckTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FraudRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudServiceServer).CheckTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudService_CheckTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudServiceServer).CheckTransaction(ctx, req.(*FraudRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FraudService_ReportRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiskReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudServiceServer).ReportRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudService_ReportRisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudServiceServer).ReportRisk(ctx, req.(*RiskReport))
	}
	return interceptor(ctx, in, info, handler)
}

// FraudService_ServiceDesc is the grpc.ServiceDesc for FraudService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FraudService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fraud.FraudService",
	HandlerType: (*FraudServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckTransaction",
			Handler:    _FraudService_CheckTransaction_Handler,
		},
		{
			MethodName: "ReportRisk",
			Handler:    _FraudService_ReportRisk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fraud/fraud.proto",
}
