// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/connect/connect.proto

package connect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // The user who owns this account
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                   // e.g., "standard", "express"
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`             // e.g., "US"
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	BusinessType  string                 `protobuf:"bytes,5,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"` // e.g., "individual", "company"
	Capabilities  *Capabilities          `protobuf:"bytes,6,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_connect_connect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_connect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_connect_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateAccountRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAccountRequest) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *CreateAccountRequest) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type UpdateAccountRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email              string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PayoutSettings     *PayoutSettings        `protobuf:"bytes,3,opt,name=payout_settings,json=payoutSettings,proto3" json:"payout_settings,omitempty"`
	PlatformFeePercent float64                `protobuf:"fixed64,4,opt,name=platform_fee_percent,json=platformFeePercent,proto3" json:"platform_fee_percent,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_proto_connect_connect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_connect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_connect_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateAccountRequest) GetPayoutSettings() *PayoutSettings {
	if x != nil {
		return x.PayoutSettings
	}
	return nil
}

func (x *UpdateAccountRequest) GetPlatformFeePercent() float64 {
	if x != nil {
		return x.PlatformFeePercent
	}
	return 0
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_proto_connect_connect_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_connect_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_connect_connect_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Account struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type               string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Country            string                 `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Email              string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	BusinessType       string                 `protobuf:"bytes,6,opt,name=business_type,json=businessType,proto3" json:"business_type,omitempty"`
	Status             string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"` // e.g., "active", "pending", "restricted"
	Capabilities       *Capabilities          `protobuf:"bytes,8,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	PayoutSettings     *PayoutSettings        `protobuf:"bytes,9,opt,name=payout_settings,json=payoutSettings,proto3" json:"payout_settings,omitempty"`
	PlatformFeePercent float64                `protobuf:"fixed64,10,opt,name=platform_fee_percent,json=platformFeePercent,proto3" json:"platform_fee_percent,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_connect_connect_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_connect_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_connect_connect_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Account) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Account) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Account) GetBusinessType() string {
	if x != nil {
		return x.BusinessType
	}
	return ""
}

func (x *Account) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Account) GetCapabilities() *Capabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Account) GetPayoutSettings() *PayoutSettings {
	if x != nil {
		return x.PayoutSettings
	}
	return nil
}

func (x *Account) GetPlatformFeePercent() float64 {
	if x != nil {
		return x.PlatformFeePercent
	}
	return 0
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Capabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transfers     bool                   `protobuf:"varint,1,opt,name=transfers,proto3" json:"transfers,omitempty"`                           // Ability to receive transfers
	CardPayments  bool                   `protobuf:"varint,2,opt,name=card_payments,json=cardPayments,proto3" json:"card_payments,omitempty"` // Ability to process card payments
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_proto_connect_connect_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_connect_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_proto_connect_connect_proto_rawDescGZIP(), []int{4}
}

func (x *Capabilities) GetTransfers() bool {
	if x != nil {
		return x.Transfers
	}
	return false
}

func (x *Capabilities) GetCardPayments() bool {
	if x != nil {
		return x.CardPayments
	}
	return false
}

type PayoutSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      string                 `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`                                  // e.g., "daily", "weekly", "manual"
	BankAccountId string                 `protobuf:"bytes,2,opt,name=bank_account_id,json=bankAccountId,proto3" json:"bank_account_id,omitempty"` // ID of the bank account where payouts are sent
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayoutSettings) Reset() {
	*x = PayoutSettings{}
	mi := &file_proto_connect_connect_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayoutSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayoutSettings) ProtoMessage() {}

func (x *PayoutSettings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_connect_connect_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayoutSettings.ProtoReflect.Descriptor instead.
func (*PayoutSettings) Descriptor() ([]byte, []int) {
	return file_proto_connect_connect_proto_rawDescGZIP(), []int{5}
}

func (x *PayoutSettings) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *PayoutSettings) GetBankAccountId() string {
	if x != nil {
		return x.BankAccountId
	}
	return ""
}

var File_proto_connect_connect_proto protoreflect.FileDescriptor

const file_proto_connect_connect_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/connect/connect.proto\x12\aconnect\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd3\x01\n" +
	"\x14CreateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12#\n" +
	"\rbusiness_type\x18\x05 \x01(\tR\fbusinessType\x129\n" +
	"\fcapabilities\x18\x06 \x01(\v2\x15.connect.CapabilitiesR\fcapabilities\"\xb0\x01\n" +
	"\x14UpdateAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12@\n" +
	"\x0fpayout_settings\x18\x03 \x01(\v2\x17.connect.PayoutSettingsR\x0epayoutSettings\x120\n" +
	"\x14platform_fee_percent\x18\x04 \x01(\x01R\x12platformFeePercent\"#\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd8\x03\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\acountry\x18\x04 \x01(\tR\acountry\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12#\n" +
	"\rbusiness_type\x18\x06 \x01(\tR\fbusinessType\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x129\n" +
	"\fcapabilities\x18\b \x01(\v2\x15.connect.CapabilitiesR\fcapabilities\x12@\n" +
	"\x0fpayout_settings\x18\t \x01(\v2\x17.connect.PayoutSettingsR\x0epayoutSettings\x120\n" +
	"\x14platform_fee_percent\x18\n" +
	" \x01(\x01R\x12platformFeePercent\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"Q\n" +
	"\fCapabilities\x12\x1c\n" +
	"\ttransfers\x18\x01 \x01(\bR\ttransfers\x12#\n" +
	"\rcard_payments\x18\x02 \x01(\bR\fcardPayments\"T\n" +
	"\x0ePayoutSettings\x12\x1a\n" +
	"\binterval\x18\x01 \x01(\tR\binterval\x12&\n" +
	"\x0fbank_account_id\x18\x02 \x01(\tR\rbankAccountId2\xd0\x01\n" +
	"\x0eConnectService\x12@\n" +
	"\rCreateAccount\x12\x1d.connect.CreateAccountRequest\x1a\x10.connect.Account\x12:\n" +
	"\n" +
	"GetAccount\x12\x1a.connect.GetAccountRequest\x1a\x10.connect.Account\x12@\n" +
	"\rUpdateAccount\x12\x1d.connect.UpdateAccountRequest\x1a\x10.connect.AccountB6Z4github.com/marwan562/fintech-ecosystem/proto/connectb\x06proto3"

var (
	file_proto_connect_connect_proto_rawDescOnce sync.Once
	file_proto_connect_connect_proto_rawDescData []byte
)

func file_proto_connect_connect_proto_rawDescGZIP() []byte {
	file_proto_connect_connect_proto_rawDescOnce.Do(func() {
		file_proto_connect_connect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_connect_connect_proto_rawDesc), len(file_proto_connect_connect_proto_rawDesc)))
	})
	return file_proto_connect_connect_proto_rawDescData
}

var file_proto_connect_connect_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_connect_connect_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),  // 0: connect.CreateAccountRequest
	(*UpdateAccountRequest)(nil),  // 1: connect.UpdateAccountRequest
	(*GetAccountRequest)(nil),     // 2: connect.GetAccountRequest
	(*Account)(nil),               // 3: connect.Account
	(*Capabilities)(nil),          // 4: connect.Capabilities
	(*PayoutSettings)(nil),        // 5: connect.PayoutSettings
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_proto_connect_connect_proto_depIdxs = []int32{
	4, // 0: connect.CreateAccountRequest.capabilities:type_name -> connect.Capabilities
	5, // 1: connect.UpdateAccountRequest.payout_settings:type_name -> connect.PayoutSettings
	4, // 2: connect.Account.capabilities:type_name -> connect.Capabilities
	5, // 3: connect.Account.payout_settings:type_name -> connect.PayoutSettings
	6, // 4: connect.Account.created_at:type_name -> google.protobuf.Timestamp
	6, // 5: connect.Account.updated_at:type_name -> google.protobuf.Timestamp
	0, // 6: connect.ConnectService.CreateAccount:input_type -> connect.CreateAccountRequest
	2, // 7: connect.ConnectService.GetAccount:input_type -> connect.GetAccountRequest
	1, // 8: connect.ConnectService.UpdateAccount:input_type -> connect.UpdateAccountRequest
	3, // 9: connect.ConnectService.CreateAccount:output_type -> connect.Account
	3, // 10: connect.ConnectService.GetAccount:output_type -> connect.Account
	3, // 11: connect.ConnectService.UpdateAccount:output_type -> connect.Account
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_connect_connect_proto_init() }
func file_proto_connect_connect_proto_init() {
	if File_proto_connect_connect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_connect_connect_proto_rawDesc), len(file_proto_connect_connect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_connect_connect_proto_goTypes,
		DependencyIndexes: file_proto_connect_connect_proto_depIdxs,
		MessageInfos:      file_proto_connect_connect_proto_msgTypes,
	}.Build()
	File_proto_connect_connect_proto = out.File
	file_proto_connect_connect_proto_goTypes = nil
	file_proto_connect_connect_proto_depIdxs = nil
}
