// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/ledger/ledger.proto

package ledger

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // e.g. "asset", "liability", "revenue", "expense"
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	ZoneId        string                 `protobuf:"bytes,4,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateAccountRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *CreateAccountRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateAccountResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RecordTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // In cents
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,5,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"` // e.g. PaymentIntent ID
	ZoneId        string                 `protobuf:"bytes,6,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Mode          string                 `protobuf:"bytes,7,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTransactionRequest) Reset() {
	*x = RecordTransactionRequest{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTransactionRequest) ProtoMessage() {}

func (x *RecordTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTransactionRequest.ProtoReflect.Descriptor instead.
func (*RecordTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *RecordTransactionRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RecordTransactionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RecordTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RecordTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecordTransactionRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *RecordTransactionRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *RecordTransactionRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type RecordTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTransactionResponse) Reset() {
	*x = RecordTransactionResponse{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTransactionResponse) ProtoMessage() {}

func (x *RecordTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTransactionResponse.ProtoReflect.Descriptor instead.
func (*RecordTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *RecordTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RecordTransactionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BulkRecordRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Transactions  []*RecordTransactionRequest `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkRecordRequest) Reset() {
	*x = BulkRecordRequest{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRecordRequest) ProtoMessage() {}

func (x *BulkRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRecordRequest.ProtoReflect.Descriptor instead.
func (*BulkRecordRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *BulkRecordRequest) GetTransactions() []*RecordTransactionRequest {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type BulkRecordResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Responses     []*RecordTransactionResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkRecordResponse) Reset() {
	*x = BulkRecordResponse{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkRecordResponse) ProtoMessage() {}

func (x *BulkRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkRecordResponse.ProtoReflect.Descriptor instead.
func (*BulkRecordResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *BulkRecordResponse) GetResponses() []*RecordTransactionResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccountResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *GetAccountResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetAccountResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_proto_ledger_ledger_proto protoreflect.FileDescriptor

const file_proto_ledger_ledger_proto_rawDesc = "" +
	"\n" +
	"\x19proto/ledger/ledger.proto\x12\x06ledger\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x87\x01\n" +
	"\x14CreateAccountRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x17\n" +
	"\azone_id\x18\x04 \x01(\tR\x06zoneId\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\"N\n" +
	"\x15CreateAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xdf\x01\n" +
	"\x18RecordTransactionRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12!\n" +
	"\freference_id\x18\x05 \x01(\tR\vreferenceId\x12\x17\n" +
	"\azone_id\x18\x06 \x01(\tR\x06zoneId\x12\x12\n" +
	"\x04mode\x18\a \x01(\tR\x04mode\"Z\n" +
	"\x19RecordTransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"Y\n" +
	"\x11BulkRecordRequest\x12D\n" +
	"\ftransactions\x18\x01 \x03(\v2 .ledger.RecordTransactionRequestR\ftransactions\"U\n" +
	"\x12BulkRecordResponse\x12?\n" +
	"\tresponses\x18\x01 \x03(\v2!.ledger.RecordTransactionResponseR\tresponses\"2\n" +
	"\x11GetAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\"\xa4\x01\n" +
	"\x12GetAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xe4\x03\n" +
	"\rLedgerService\x12x\n" +
	"\x16BulkRecordTransactions\x12\x19.ledger.BulkRecordRequest\x1a\x1a.ledger.BulkRecordResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/ledger/bulk-transactions\x12|\n" +
	"\x11RecordTransaction\x12 .ledger.RecordTransactionRequest\x1a!.ledger.RecordTransactionResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/ledger/transactions\x12l\n" +
	"\rCreateAccount\x12\x1c.ledger.CreateAccountRequest\x1a\x1d.ledger.CreateAccountResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/ledger/accounts\x12m\n" +
	"\n" +
	"GetAccount\x12\x19.ledger.GetAccountRequest\x1a\x1a.ledger.GetAccountResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /v1/ledger/accounts/{account_id}B5Z3github.com/sapliy/fintech-ecosystem/proto/ledgerb\x06proto3"

var (
	file_proto_ledger_ledger_proto_rawDescOnce sync.Once
	file_proto_ledger_ledger_proto_rawDescData []byte
)

func file_proto_ledger_ledger_proto_rawDescGZIP() []byte {
	file_proto_ledger_ledger_proto_rawDescOnce.Do(func() {
		file_proto_ledger_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_ledger_proto_rawDesc), len(file_proto_ledger_ledger_proto_rawDesc)))
	})
	return file_proto_ledger_ledger_proto_rawDescData
}

var file_proto_ledger_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_ledger_ledger_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),      // 0: ledger.CreateAccountRequest
	(*CreateAccountResponse)(nil),     // 1: ledger.CreateAccountResponse
	(*RecordTransactionRequest)(nil),  // 2: ledger.RecordTransactionRequest
	(*RecordTransactionResponse)(nil), // 3: ledger.RecordTransactionResponse
	(*BulkRecordRequest)(nil),         // 4: ledger.BulkRecordRequest
	(*BulkRecordResponse)(nil),        // 5: ledger.BulkRecordResponse
	(*GetAccountRequest)(nil),         // 6: ledger.GetAccountRequest
	(*GetAccountResponse)(nil),        // 7: ledger.GetAccountResponse
	(*timestamppb.Timestamp)(nil),     // 8: google.protobuf.Timestamp
}
var file_proto_ledger_ledger_proto_depIdxs = []int32{
	2, // 0: ledger.BulkRecordRequest.transactions:type_name -> ledger.RecordTransactionRequest
	3, // 1: ledger.BulkRecordResponse.responses:type_name -> ledger.RecordTransactionResponse
	8, // 2: ledger.GetAccountResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: ledger.LedgerService.BulkRecordTransactions:input_type -> ledger.BulkRecordRequest
	2, // 4: ledger.LedgerService.RecordTransaction:input_type -> ledger.RecordTransactionRequest
	0, // 5: ledger.LedgerService.CreateAccount:input_type -> ledger.CreateAccountRequest
	6, // 6: ledger.LedgerService.GetAccount:input_type -> ledger.GetAccountRequest
	5, // 7: ledger.LedgerService.BulkRecordTransactions:output_type -> ledger.BulkRecordResponse
	3, // 8: ledger.LedgerService.RecordTransaction:output_type -> ledger.RecordTransactionResponse
	1, // 9: ledger.LedgerService.CreateAccount:output_type -> ledger.CreateAccountResponse
	7, // 10: ledger.LedgerService.GetAccount:output_type -> ledger.GetAccountResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_ledger_ledger_proto_init() }
func file_proto_ledger_ledger_proto_init() {
	if File_proto_ledger_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_ledger_proto_rawDesc), len(file_proto_ledger_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_ledger_proto_goTypes,
		DependencyIndexes: file_proto_ledger_ledger_proto_depIdxs,
		MessageInfos:      file_proto_ledger_ledger_proto_msgTypes,
	}.Build()
	File_proto_ledger_ledger_proto = out.File
	file_proto_ledger_ledger_proto_goTypes = nil
	file_proto_ledger_ledger_proto_depIdxs = nil
}
